os:
  - windows
  - linux
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
stages:
  - build
  #- release

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: 
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script: pyinstaller comparator.py --onefile
#python3 comparator.py || python comparator.py