language: python
branches:
  except:
  - /^untagged/
jobs:
  include:
  - name: Python 3.7.4 on macOS
    os: osx
    osx_image: xcode11.2
    language: shell
  - name: Python 3.7.4 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.4
    - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
- pip3 install --upgrade pip
- pip3 install -r requirements.txt
script: pyinstaller comparator.py --onefile

before_deploy:
  - export TRAVIS_TAG="1.$TRAVIS_BUILD_NUMBER"
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: RiiBYyry5qjE/OsYAYZ6Ub6XxRnNsmglCD4stbQN92U3gI2Ey4w2i8opZ7aLn/GtspWC9OmVvzimR4vFQeL4WkZpM9ktg5V2HFiCQMh5gJdPmFbaj+cDKvOLJ5sTSXibGUw7WF+ygzt0R1UweCpyKwQjlTygKpSCz3UldMYTud0ViLhWcthIvhx0sk8KYIkxH6+N6HkLPsvPdPdxcBM21J9bbJgAH1TaGIn66nzf7j5+0LegE3yvO9sK1fsHNEKeHnaFMzJcUkzNGFCNoqcMAG6qIEitw7l3pxwV9JWyMP/GRrBoVGUUt6O71g7igfymcuixqJMbdK1CGA3OOYg/egVs5HSZGPafyFKWp75JWPSw8UrCROAimhnQXsXZzaL/teS9lfxYvlEK6OdXbFcuFKyzBf+KDoMKX2BJjyI8pDxhhiZTrcArdQwZjwLF/my683TUNnLP2kczewbYpwMc7uuyXshwaqTK+m5piL4pmJ5e4RP9OTq1MG8l6C+Mb2nrSBaWiKFXGFXiLTI1wus0D5pWcp7B4lUxwafuR2/HgJyKCqjAOLjwXDrl240/kAS06EdsXXKEFOvwuRgHpI7/F8EspjJlR/HPneix5/LP16PXK5qnM3HKuHXZEjPso65zwuuDyXu3ok9JQ7A71NigXOGmV8wQOO1caPtqHvGFQ8E=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: vsanjay85/pycompare
    branches:
      only:
        - master   
